config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Root page about page
  root 'pages#home'
  get 'about',to: 'pages#about'
  # Sign up page
  get 'signup',to: 'users#new'

  # Create sessiong
  get 'login',to: 'sessions#new'
  post 'login',to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'

  # Users and articles papge
  resources :users, except: [:new]
  resources :articles
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_categories
  has_many :categories, through: :article_categories

  belongs_to :user
  validates :title,
    presence: true,
    length: {
      minimum: 3,
      maximum: 250
    }
  validates :description,
    presence: true,
    length: {
      minimum: 3,
      maximum: 2000
    }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true,
    uniqueness: true,
    length: {minimum: 4,maximum: 25}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save {self.email = email.downcase}
  validates :username, presence: true,
    length:{minimum: 3, maximum: 25},
    uniqueness: {case_sensitive: false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
    length:{maximum:100},
    uniqueness: {case_sensitive: false},
    format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit,:update,:show,:destroy]
  before_action :require_user, except: [:index,:show]
  before_action :require_same_user, only: [:edit,:update,:destroy]
  def index
      @articles = Article.all.page(params[:page]).per(5)
  end

  def new
    @article = Article.new
  end

  def edit
    # set_article
  end

  def update
    # set_article
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render :edit
    end

  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def show
    # set_article
  end

  def destroy
    # set_article
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end
  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title,:description,category_ids: [])
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index,:show]

  def index
    @categories = Category.all.page(params[:page]).per(5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "New category has been successfully created"
      redirect_to categories_path
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update,:destroy]
  before_action :require_same_user, only: [:edit,:update,:destroy]
  before_action :require_admin, only: [:destroy]

  def index
      @users = User.all.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "New user has been created"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user_articles = @user.articles.page(params[:page]).per(5)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User account has successfully edited"
      redirect_to articles_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:danger] = "You can only change your profile"
      redirect_to articles_path
    end
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user,options={size:80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 center jumbotron">
      <div class="article-title">
        <%= link_to article.title, article_path(article) %>
      </div>
      <hr>
      <div class="arcicle-body">
        <%= truncate(article.description, length: 500) %>
      </div></br>
      <% if article.categories.any? %>
        <p>Categories: <%= render article.categories %></p>
      <% end %>
      <hr>
      <div class="article-meta-details">
        <small>
          Created by:<%= link_to article.user.username , user_path(article.user) if article.user %>
          <%=time_ago_in_words(article.created_at)%> ago,
          last updated: <%=time_ago_in_words(article.updated_at)%> ago
        </small>
      </div>
      <hr>
      <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <div class="article-actions" align="center">
          <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(article), method: :delete,
                        data: { confirm: "Are you sure you want to delete the article?"},
                        class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-2"></div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<!-- Display article errors  -->
<!-- <%= render 'share/errors', obj: @article %> -->
<%= render 'share/errors', obj: @article %>
<!-- Form for create new article  -->
<div class="row">

    <%= form_for @article do |f| %>
      <div class="form-group row">
        <div class="control-label col-sm-3">
          <%= f.label :title, "Title",class:"fit-right" %></br>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control",placeholder: "Title of article", autofocus: true %><br/>
        </div>
      </div>
      <div class="form-group row">
        <div class="control-label col-sm-3">
          <%= f.label :description, "Description", class: "fit-right" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, size: "90x12"  ,class:"form-control",placeholder:"Body of article" %><br/>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-3"></div>
        <div class="col-sm-9">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
           <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
          <% end %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-3"></div>
        <div class="col-sm-3">
            <%= f.submit class: "btn btn-primary btn-lg" %><br/>
        </div>
        [<%= link_to "Cancel request and return to articles listing", articles_path %>]
      </div>

    <% end %>


</div>

app/views/articles/edit.html.erb
<h1 align="center" style="font-size:3em; font-weight:bold;">Update an article</h1>
</br>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center" style="font-size:3em; font-weight:bold;">Listing all articles</h1>
<%= render 'article', obj: @articles %>
<%= paginate @articles, theme: 'twitter-bootstrap-4' %>

app/views/articles/new.html.erb
<h1 align="center" style="font-size:3em; font-weight:bold;">Create an article</h1>
</br>
<%= render 'form' %>

app/views/articles/show.html.erb
</br><h2 align="center">Title: <%= @article.title %></h2></br>
<div class="row" >
  <div class="col-md-2"></div>
  <div class="well col-md-8 ">
    <h4 class="center"><strong>Description</strong></h4>
    <hr>
    <div class="jumbotron">
      <%= simple_format(@article.description) %></br>
      <% if @article.categories.any? %>
        <p>Categories: <%= render @article.categories %></p>
      <% end %>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>
<div class="article-actions" align="center">
  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete this article", article_path(@article), method: :delete,
                  data: { confirm: "Are you sure you want to delete the article?"},
                  class: "btn btn-xs btn-danger" %>
  <% end %>
  <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>

</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %>  </span>

app/views/categories/_form.html.erb
<!-- Display category errors  -->
<%= render 'share/errors', obj: @category%>
<!-- Form for category new user  -->
<div class="row">
  <%= form_for @category do |f| %>
    <div class="form-group row">
      <div class="control-label col-sm-3">
        <%= f.label :name, "Category name",class:"fit-right" %></br>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :name, size: "90x1" ,class: "form-control",placeholder: "Enter an category name", autofocus: true %><br/>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-3"></div>
      <div class="col-sm-3">
          <%= f.submit class:"btn btn-primary btn-lg"%><br/>
      </div>
      [<%= link_to "Cancel request and return to articles listing", articles_path %>]
      </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<h1 align="center" style="font-size:3em; font-weight:bold;">Edit new category</h1></br>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center" style="font-size:2em; font-weight:bold;">Listing all categories</h1></br>

<div align="center">
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 jumbotron">
          <li class="article-title"><%= link_to category.name, category_path(category) %></li>
          <li><small><%= pluralize(category.articles.count, "article") %></small></li>
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Edit category", edit_category_path(category), class: "btn btn-xs btn-primary" %>
          <% end %>
        </div>
        <div class="col-md-3"></div>
      </div>
  <% end %>
  <%= paginate @categories, theme: 'twitter-bootstrap-4' %>
</div>

app/views/categories/new.html.erb
<h1 align="center" style="font-size:3em; font-weight:bold;">Create new category</h1></br>

<%= render 'form' %>

app/views/categories/show.html.erb
<div align="center">
  </br></br>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 jumbotron">
      <%= link_to @category.name, category_path(@category), style: "font-size: 2em; font-weight: bold;" %></br>
      <small><%= pluralize(@category.articles.count, "article") %></small></br>
      <% if logged_in? && current_user.admin? %>
        <%= link_to "Edit category", edit_category_path(@category), class: "btn btn-xs btn-primary" %>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">

  <footer class="footer">
    <small>
      Copyright © <a href="#">The Complete Ruby on Rails Developer</a> by <a href="#">Mashrur Hossain</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>

</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm-12 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%=link_to "Articles", articles_path,class: "nav-link text-white"  %><span class="sr-only">(current)</span></li>
      <li class="nav-item"><%=link_to "Users", users_path,class: "nav-link text-white"  %><span class="sr-only">(current)</span></li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All categories", categories_path, class: "dropdown-item" %>
          <% Category.all.each do |category| %>
            <%= link_to category.name, category_path(category), class: "dropdown-item" %>
          <% end %>
          <div class="dropdown-divider"></div>
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <li>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </li>
    </ul>
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Log out", logout_path, method: :delete,
          data: {confirm: "Are you sure to log out"}, class: "nav-link text-white" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Your Profile <%= "(Admin)" if current_user.admin? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log in", login_path, class: "nav-link text-white" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Load Facebook SDK for JavaScript -->
      <div id="fb-root"></div>
      <script>
        window.fbAsyncInit = function() {
          FB.init({
            xfbml            : true,
            version          : 'v6.0'
          });
        };

        (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>

      <!-- Your customer chat code -->
      <div class="fb-customerchat"
        attribution=setup_tool
        page_id="104573871156779"
  theme_color="#0084ff"
  logged_in_greeting="Hi! How can we help you? Welcome you to ours page"
  logged_out_greeting="Hi! How can we help you? Welcome you to ours page">
      </div>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
    <!-- <%= debug(params) if Rails.env.development? %> -->
  
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>

app/views/pages/home.html.erb
<div class="center jumbotron" id="home">
  <h1>ALPHA BLOG</h1>
  <%= link_to "Sign up now",signup_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/share/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-8">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </h3>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<!-- Display user errors  -->
<%= render 'share/errors', obj: @user%>
<!-- Form for create new user  -->
<div class="row">

    <%= form_for @user do |f| %>
      <div class="form-group row">
        <div class="control-label col-sm-3">
          <%= f.label :username, "Username",class:"fit-right" %></br>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control",placeholder: "Enter an username", autofocus: true %><br/>
        </div>
      </div>
      <div class="form-group row">
        <div class="control-label col-sm-3">
          <%= f.label :email, "Email", class: "fit-right" %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, size: "90x1"  ,class:"form-control",placeholder:"Enter an email" %><br/>
        </div>
      </div>
      <div class="form-group row">
        <div class="control-label col-sm-3">
          <%= f.label :password, "Password", class: "fit-right" %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password ,class:"form-control",placeholder:"Enter a password" %><br/>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-3"></div>
        <div class="col-sm-3">
            <%= f.submit(@user.new_record? ? "Sign up": "Update account", class:"btn btn-primary btn-lg")%><br/>
        </div>
        [<%= link_to "Cancel request and return to articles listing", articles_path %>]
        </div>

    <% end %>


</div>

app/views/users/edit.html.erb
<h1 align="center" style="font-size:3em; font-weight:bold;">Edit user account</h1></br>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center" style="font-size:3em; font-weight:bold;">Users Listing</h1></br>
<div align="center">
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 jumbotron">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="article-title"><%= link_to user.username, user_path(user) %></li>
          <li><small><%= pluralize(user.articles.count,"article")%></small></li>
          <% if logged_in? and current_user.admin? %>
            <li><%= link_to "Delete this user", user_path(user), method: :delete,
                data: { confirm: "Are you sure you want to delete the user and all their articles?" } %></li>
          <% end %>
        </div>
        <div class="col-md-3"></div>
      </div>
  <% end %>
  <%= paginate @users, theme: 'twitter-bootstrap-4' %>
</div>

app/views/users/new.html.erb
<h1 align="center" style="font-size:3em; font-weight:bold;">Create new user</h1></br>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center" style="font-size:2em; font-weight:bold;">Welcome to <%= @user.username %>'s page </h1>
</br>
<div class="row">
  <div class="center">
    <%= gravatar_for @user, size: 100 %>
  </div>
</div>
<h4 align="center"><%= @user.username%>'s articles</h4>
<%= render 'articles/article',obj: @user_articles %>
<%= paginate @user_articles, theme: 'twitter-bootstrap-4'%>